---
title: "C9orf72 mice - Y-maze analysis"
output:html_document
date: "2025-02-05"
---
***Load libraries and data***

```{r}
library(readr)
library(forcats)
library(lme4)
library(ggplot2)
library(lmerTest)
library(emmeans)
library(ggResidpanel)
library(plyr)
library(dplyr)
library(tidyr)
library(car)
library(ggsignif)
library(table1)
#Set working directory to location of files, if not the same

setwd("~/Desktop/Data/Y-maze/")

```

```{r}


#***Pre-processing***#

#Add genotype information#
df <- read_csv("C9ORF-BEHAV_Y-Maze_processed_data.csv")
df1<- within(df, rm(genotype))
df_gen <- read_csv("C9orf72GR400-genotype.csv")
joined_df1 <- left_join(df1, df_gen, by = "animal_name")

df2 <- joined_df1 %>% pivot_wider(names_from = parameter, values_from = data)
colnames(df2)[colnames(df2) == "stock"] <- "inh"

write.csv(df2, "Y-maze-pivoted-C9.csv", row.names = FALSE)


#Calculate distances and novel preference ratios (NPRs) from relevant raw data columns

#Calculate overall dist moved - habituation
df2$`dist_hab_overall` <- df2$`Distance moved total/time:1/phase:Habituation` +  df2$`Distance moved total/time:2/phase:Habituation` + 
                               df2$`Distance moved total/time:3/phase:Habituation` +  df2$`Distance moved total/time:4/phase:Habituation` + df2$`Distance moved total/time:5/phase:Habituation`

#Calculate overall dist moved - test
df2$`dist_test_overall` <- df2$`Distance moved total/time:1/phase:Novel` + 
                                  df2$`Distance moved total/time:2/phase:Novel`

#Calculate NPR based on time
df2$NPRtime <- (df2$`Novel arm Duration/time:1/phase:Novel` + df2$`Novel arm Duration/time:2/phase:Novel`)/(df2$`Novel arm Duration/time:1/phase:Novel` + df2$`Novel arm Duration/time:2/phase:Novel`+df2$`Familiar arm Duration/time:1/phase:Novel`+df2$`Familiar arm Duration/time:2/phase:Novel`)

#Calculate NPR based on frequency
df2$NPRfreq <-(df2$`Novel arm Frequency/time:1/phase:Novel` + df2$`Novel arm Frequency/time:2/phase:Novel`)/(df2$`Novel arm Frequency/time:1/phase:Novel` + df2$`Novel arm Frequency/time:2/phase:Novel`+df2$`Familiar arm Frequency/time:1/phase:Novel`+df2$`Familiar arm Frequency/time:2/phase:Novel`)
print(colnames(df2))

df_new <- df2 %>% mutate(across(c('NPRtime', 'NPRfreq'), ~ round(.x, 4)))

write.csv(df_new, "updated_Y-maze-pre-processed-C9.csv", row.names = FALSE)
# Display the updated DataFrame


```
***Read data for statistical analysis***
```{r}      

# read in data 

data_mouse <- read_csv("updated_Y-maze-pre-processed-C9.csv", col_types = cols (
  animal_name = 'f',
  genotype = 'f',
  sex = 'f',
  inh = 'f',
  mean_experimental_age = 'f'
))

data_mouse$genotypeordered <- ordered(data_mouse$genotype, levels=c("C9ORF72-GR400-B6J:WT", "C9ORF72-GR400-B6J:Het"))
data_mouse$mean_experimental_age <- as.factor(data_mouse$mean_experimental_age)
data_mouse$genotype <- as.factor(data_mouse$genotype)
data_mouse$sex <- as.factor(data_mouse$sex)
data_mouse$inh <- as.factor(data_mouse$inh)


table1::label(data_mouse$genotype) <- "genotype"
table1::label(data_mouse$sex) <- "sex"
table1::label(data_mouse$mean_experimental_age) <- "age"
	
table1::table1(~  mean_experimental_age | genotype, data = data_mouse)


```

***LMER - distance traveled during habituation***
```{r}
#relevel the data to compare everything in the model to control mice
data_mouse$genotype <- relevel(data_mouse$genotype, ref = "C9ORF72-GR400-B6J:WT")

#linear mixed effects model 
ME_EXPL_hd<- lmer(dist_hab_overall~genotype*(mean_experimental_age + sex + inh) + (1|animal_name),data = data_mouse)
summary(ME_EXPL_hd)
resid_panel(ME_EXPL_hd) 
anova(ME_EXPL_hd, type=3)
#Post-hoc - relevant contrasts
emm_hd <- emmeans(ME_EXPL_hd, ~genotype*mean_experimental_age)
str(emm_hd)
coef_t_hd <- coef(pairs(emm_hd))
custom_contrasts_hd <- list("Wt 12.5 vs 64.5 weeks" = c(1, 0, -1, 0),
                         "Het 12.5 vs 64.5 weeks" = c(0, 1, 0, -1)
                         )
specific_comparisons_hd <-contrast(emm_hd, custom_contrasts_hd)
summary_comparisons_hd <- summary(specific_comparisons_hd, adjust="bonferroni")
print(summary_comparisons_hd)

```

***LMER - distance traveled during test***
```{r}
#relevel the data to compare everything in the model to control mice
data_mouse$genotype <- relevel(data_mouse$genotype, ref = "C9ORF72-GR400-B6J:WT")

#linear mixed effects model
ME_EXPL_novel<- lmer(dist_test_overall~genotype*(mean_experimental_age + sex + inh) + (1|animal_name),data = data_mouse)
summary(ME_EXPL_novel)
resid_panel(ME_EXPL_novel) 
anova(ME_EXPL_novel, type=3)
#Post-hoc - relevant contrasts
emm_novel <- emmeans(ME_EXPL_novel, ~genotype*mean_experimental_age)
str(emm_novel)
coef_t_novel <- coef(pairs(emm_novel))
custom_contrasts_novel <- list("Wt 12.5 vs 64.5 weeks" = c(1, 0, -1, 0),
                         "Het 12.5 vs 64.5 weeks" = c(0, 1, 0, -1)
                         )
specific_comparisons_novel <-contrast(emm_novel, custom_contrasts_novel)
summary_comparisons_novel <- summary(specific_comparisons_novel, adjust="bonferroni")

p_value_novel <- summary_comparisons_novel$p.value
print(p_value_novel)
print(summary_comparisons_novel)

```

***Plot - Habituation distance***
```{r}
# take means and se per group 
EXPL_habituation <- ddply(data_mouse, c("mean_experimental_age", "genotype"), summarise,
               N    = length(dist_hab_overall),
               mean = mean(dist_hab_overall, na.rm = TRUE),
               sd   = sd(dist_hab_overall, na.rm = TRUE),
               se   = sd / sqrt(N)
)

# Ensure the factor levels are ordered as desired
EXPL_habituation$mean_experimental_age <- factor(EXPL_habituation$mean_experimental_age, levels = c("12.5", "64.5"))
data_mouse$mean_experimental_age <- factor(data_mouse$mean_experimental_age, levels = c("12.5", "64.5"))

# Combine genotype and age for the x-axis and set specific levels to control order and spacing
EXPL_habituation$genotype_age <- factor(paste(EXPL_habituation$genotype, EXPL_habituation$mean_experimental_age, sep = "_"),
                                  levels = c("C9ORF72-GR400-B6J:WT_12.5", "C9ORF72-GR400-B6J:WT_64.5", 
                                             "C9ORF72-GR400-B6J:Het_12.5", "C9ORF72-GR400-B6J:Het_64.5"))
data_mouse$genotype_age <- factor(paste(data_mouse$genotype, data_mouse$mean_experimental_age, sep = "_"),
                                levels = c("C9ORF72-GR400-B6J:WT_12.5", "C9ORF72-GR400-B6J:WT_64.5", 
                                           "C9ORF72-GR400-B6J:Het_12.5", "C9ORF72-GR400-B6J:Het_64.5"))
# Plot averages per group
pEXPL_habituation <- ggplot(EXPL_habituation, aes(x = genotype_age, y = mean, colour = genotype)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.3), width = 0.5, alpha = 0) + 
  geom_jitter(data = data_mouse, aes(x = genotype_age, y = dist_hab_overall, colour = genotype, shape = mean_experimental_age), 
              position = position_jitterdodge(jitter.width = 0.5, dodge.width = 0.3), size = 0.8) + # Add individual data points
  
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), 
                width = 0.2, position = position_dodge(0.75), colour = "black") + # Add error bars
  # Add a dummy line layer for the legend
  ylab("Total distance travelled (mm) - habitutation") + # sets the y-axis label
  scale_y_continuous(breaks = seq(0, 40000, by = 10000), limits = c(0, 40000), expand = c(0, 0)) +  # Set y-axis breaks with step size of 0.1
  xlab(NULL) + # sets the x-axis label
  scale_x_discrete(labels = c(
    "C9ORF72-GR400-B6J:WT_12.5" = bquote(bold(atop("WT", "12.5 wk"))),
    "C9ORF72-GR400-B6J:WT_64.5" = bquote(bold(atop("WT", "64.5 wk"))),
    "C9ORF72-GR400-B6J:Het_12.5" = bquote(atop(bolditalic("C9orf72")^bolditalic("GR400/+"), bold("12.5 wk"))),
    "C9ORF72-GR400-B6J:Het_64.5" = bquote(atop(bolditalic("\u2003C9orf72")^bolditalic("GR400/+"), bold("64.5 wk")))
  ))+ # Custom labels for genotype and age
  theme_classic(base_size = 8) + # classic theme makes white background without lines, sets base font size to 14 pt
  theme(
    text = element_text(family = "Arial"),
    legend.position = c(0.35, 0.925), # Position legend within plotting space
        legend.direction = "horizontal", # Arrange legend items horizontally
        legend.text.align = 0,
        legend.spacing.y = unit(0, "cm"), # Remove vertical spacing between items
        legend.margin = margin(0, 0, 0, 0)  ,      
        legend.text = element_text(size = 8, family = "Arial"), # Set font size for legend text
        legend.title = element_text(size = 8, face = "bold", family = "Arial"), # Set font size for legend title
        axis.title.y = element_text(size = 8, face = "bold", family = "Arial"), 
  axis.text.x = element_text(size = 8, colour="black", family = "Arial"), # Adjust vertical alignment        
  axis.text.y = element_text(size = 8, colour = "black", family = "Arial"),
        legend.background = element_rect(fill = NA, colour = NA)) + # Rotate x-axis labels for better readability
  scale_colour_manual(name = NULL, # sets the legend title     
                      breaks = c("C9ORF72-GR400-B6J:WT", "C9ORF72-GR400-B6J:Het"), # sets the order of items in the legend
                      labels = c("WT", expression(italic("C9orf72")^italic("GR400/+"))), # sets the labels of items in the legend
                      values = c("#009E73", "#332288")) + # set line colours for points
  scale_shape_manual(name = "Age (weeks)", # sets the legend title for shape
                     values = c("12.5" = 1, "64.5" = 16))+  # set shapes for ages (1 = empty circle, 16 = filled circle)
  guides(
    colour = guide_legend(order = 1, override.aes = list(shape=NA)), # Use only lines for Genotype
    shape = guide_legend(order = 2) # Keep shape legend for Age (weeks)
  )


# Save the plot
ggsave("C9_hab_dist_av_600_col-arial.tiff", plot = pEXPL_habituation, width = 3.5, height = 3, dpi = 600)  # Adjust width, height, and dpi as needed and save the image in the folder where the code file is

# Display the plot
pEXPL_habituation


```


***Plot - Test distance***
```{r}
# take means and se per group 


EXPL_novel <- ddply(data_mouse, c("mean_experimental_age", "genotype"), summarise,
               N    = length(dist_test_overall),
               mean = mean(dist_test_overall, na.rm = TRUE),
               sd   = sd(dist_test_overall, na.rm = TRUE),
               se   = sd / sqrt(N)
)

# Plot averages per group
# Ensure the factor levels are ordered as desired
EXPL_novel$mean_experimental_age <- factor(EXPL_novel$mean_experimental_age, levels = c("12.5", "64.5"))
data_mouse$mean_experimental_age <- factor(data_mouse$mean_experimental_age, levels = c("12.5", "64.5"))

# Combine genotype and age for the x-axis and set specific levels to control order and spacing
EXPL_novel$genotype_age <- factor(paste(EXPL_novel$genotype, EXPL_novel$mean_experimental_age, sep = "_"),
                                  levels = c("C9ORF72-GR400-B6J:WT_12.5", "C9ORF72-GR400-B6J:WT_64.5", 
                                             "C9ORF72-GR400-B6J:Het_12.5", "C9ORF72-GR400-B6J:Het_64.5"))
data_mouse$genotype_age <- factor(paste(data_mouse$genotype, data_mouse$mean_experimental_age, sep = "_"),
                                levels = c("C9ORF72-GR400-B6J:WT_12.5", "C9ORF72-GR400-B6J:WT_64.5", 
                                           "C9ORF72-GR400-B6J:Het_12.5", "C9ORF72-GR400-B6J:Het_64.5"))

# Plot averages per group
pEXPL_novel <- ggplot(EXPL_novel, aes(x = genotype_age, y = mean, colour = genotype)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.3), width = 0.5, alpha = 0) + 
  geom_jitter(data = data_mouse, aes(x = genotype_age, y = dist_test_overall, colour = genotype, shape = mean_experimental_age), 
              position = position_jitterdodge(jitter.width = 0.5, dodge.width = 0.3), size = 0.8) + # Add individual data points
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), 
                width = 0.2, position = position_dodge(0.75), colour = "black") + # Add error bars
  # Add a dummy line layer for the legend
  ylab("Total distance travelled (mm) - test") + # sets the y-axis label
  scale_y_continuous(breaks = seq(0, 40000, by = 10000), limits = c(0, 40000), expand = c(0, 0)) +  # Set y-axis breaks with step size of 0.1
  xlab(NULL) + # sets the x-axis label
  scale_x_discrete(labels = c(
    "C9ORF72-GR400-B6J:WT_12.5" = bquote(bold(atop("WT", "12.5 wk"))),
    "C9ORF72-GR400-B6J:WT_64.5" = bquote(bold(atop("WT", "64.5 wk"))),
    "C9ORF72-GR400-B6J:Het_12.5" = bquote(atop(bolditalic("C9orf72")^bolditalic("GR400/+"), bold("12.5 wk"))),
    "C9ORF72-GR400-B6J:Het_64.5" = bquote(atop(bolditalic("\u2003C9orf72")^bolditalic("GR400/+"), bold("64.5 wk")))
  ))+ # Custom labels for genotype and age
  theme_classic(base_size = 8) + # classic theme makes white background without lines, sets base font size to 14 pt
  theme(
    text = element_text(family = "Arial"),
    legend.position = c(0.35, 0.92), # Position legend within plotting space
        legend.direction = "horizontal", # Arrange legend items horizontally
        legend.text.align = 0,
        legend.spacing.y = unit(0, "cm"), # Remove vertical spacing between items
        legend.margin = margin(0, 0, 0, 0)  ,      
        legend.text = element_text(size = 8, family = "Arial"), # Set font size for legend text
        legend.title = element_text(size = 8, face = "bold", family = "Arial"), # Set font size for legend title
        axis.title.y = element_text(size = 8, face = "bold", family = "Arial"), 
  axis.text.x = element_text(size = 8, colour="black", family = "Arial"), # Adjust vertical alignment        
  axis.text.y = element_text(size = 8, colour = "black", family = "Arial"),
        legend.background = element_rect(fill = NA, colour = NA)) + # Rotate x-axis labels for better readability
  scale_colour_manual(name = NULL, # sets the legend title     
                      breaks = c("C9ORF72-GR400-B6J:WT", "C9ORF72-GR400-B6J:Het"), # sets the order of items in the legend
                      labels = c("WT", expression(italic("C9orf72")^italic("GR400/+"))), # sets the labels of items in the legend
                      values = c("#009E73", "#332288")) + # set line colours for points
  scale_shape_manual(name = "Age (weeks)", # sets the legend title for shape
                     values = c("12.5" = 1, "64.5" = 16))+  # set shapes for ages (1 = empty circle, 16 = filled circle)
  guides(
    colour = guide_legend(order = 1, override.aes = list(shape=NA)), # Use only lines for Genotype
    shape = guide_legend(order = 2) # Keep shape legend for Age (weeks)
  )

# Add significance stars using geom_signif
pEXPL_novel <- pEXPL_novel +
  geom_signif(comparisons = list(
    c("C9ORF72-GR400-B6J:Het_12.5", "C9ORF72-GR400-B6J:Het_64.5")
   #c("MAT_69.5", "PAT_69.5")
    
  ),
  annotations = c(
    ifelse(p_value_novel[2] < 0.0001, "****",
           ifelse(p_value_novel[2] < 0.001, "***",
               ifelse(p_value_novel[2] < 0.01, "**",
                  ifelse(p_value_novel[2] < 0.05, "*", ""))))
  ),
  y_position = c(15000), # Adjust positions as needed
  tip_length = 0.02, textsize = 7,
  color = "black", family = "Arial")

# Save the plot
ggsave("C9_novel_dist_av_600_col-arial.tiff", plot = pEXPL_novel, width = 3.5, height = 3, dpi = 600)  # Adjust width, height, and dpi as needed and save the image in the folder where the code file is

# Display the plot
pEXPL_novel

```


***LMER - NPR - time***

```{r}
#relevel the data to compare everything in the model to control mice
data_mouse$genotype <- relevel(data_mouse$genotype, ref = "C9ORF72-GR400-B6J:WT")

#linear mixed effects model
ME_EXPL_nprt<- lmer(NPRtime~genotype*(mean_experimental_age + sex + inh) + (1|animal_name),data = data_mouse)
summary(ME_EXPL_nprt)
resid_panel(ME_EXPL_nprt) 
anova(ME_EXPL_nprt, type=3)
#Post-hoc - relevant contrasts
emm_nprt <- emmeans(ME_EXPL_nprt, ~genotype*mean_experimental_age)
str(emm_nprt)
coef_t_nprt <- coef(pairs(emm_nprt))
custom_contrasts_nprt <- list(
                         "12.5 Wt vs Het" = c(1, -1, 0, 0),
                        "64.5 Wt vs Het" = c(0, 0, 1, -1)
                         )
specific_comparisons_nprt <-contrast(emm_nprt, custom_contrasts_nprt)
summary_comparisons_nprt <- summary(specific_comparisons_nprt, adjust="bonferroni")
print(summary_comparisons_nprt)

```


***Plot novel preference ratio from duration by age and genotype***

```{r}
# take means and se per group for plotting Duration

EXPL_NPR_t <- ddply(data_mouse, c("mean_experimental_age", "genotype"), summarise,
               N    = length(NPRtime),
               mean = mean(NPRtime, na.rm = TRUE),
               sd   = sd(NPRtime, na.rm = TRUE),
               se   = sd / sqrt(N)
)


# Ensure the factor levels are ordered as desired
EXPL_NPR_t$mean_experimental_age <- factor(EXPL_NPR_t$mean_experimental_age, levels = c("12.5", "64.5"))
data_mouse$mean_experimental_age <- factor(data_mouse$mean_experimental_age, levels = c("12.5", "64.5"))

# Combine genotype and age for the x-axis and set specific levels to control order and spacing
EXPL_NPR_t$genotype_age <- factor(paste(EXPL_NPR_t$genotype, EXPL_NPR_t$mean_experimental_age, sep = "_"),
                                  levels = c("C9ORF72-GR400-B6J:WT_12.5", "C9ORF72-GR400-B6J:WT_64.5", 
                                             "C9ORF72-GR400-B6J:Het_12.5", "C9ORF72-GR400-B6J:Het_64.5"))
data_mouse$genotype_age <- factor(paste(data_mouse$genotype, data_mouse$mean_experimental_age, sep = "_"),
                                levels = c("C9ORF72-GR400-B6J:WT_12.5", "C9ORF72-GR400-B6J:WT_64.5", 
                                           "C9ORF72-GR400-B6J:Het_12.5", "C9ORF72-GR400-B6J:Het_64.5"))

# Plot averages per group
pEXPL_NPR_t <- ggplot(EXPL_NPR_t, aes(x = genotype_age, y = mean, colour = genotype)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.3), width = 0.5, alpha = 0) + 
  geom_jitter(data = data_mouse, aes(x = genotype_age, y = NPRtime, colour = genotype, shape = mean_experimental_age), 
              position = position_jitterdodge(jitter.width = 0.5, dodge.width = 0.3), size = 0.8) + # Add individual data points
   geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey50") + # Add a dashed line at y = 0.5

   geom_errorbar(aes(ymin = mean - se, ymax = mean + se), 
                width = 0.2, position = position_dodge(0.75), colour = "black") + # Add error bars
  # Add a dummy line layer for the legend
  ylab("NPR based on time (s)") + # sets the y-axis label
  scale_y_continuous(breaks = seq(0, 1.5, by = 0.5), limits = c(0, 1.5), expand = c(0, 0)) +  # Set y-axis breaks with step size of 0.1
  xlab(NULL) + # sets the x-axis label
  scale_x_discrete(labels = c(
    "C9ORF72-GR400-B6J:WT_12.5" = bquote(bold(atop("WT", "12.5 wk"))),
    "C9ORF72-GR400-B6J:WT_64.5" = bquote(bold(atop("WT", "64.5 wk"))),
    "C9ORF72-GR400-B6J:Het_12.5" = bquote(atop(bolditalic("C9orf72")^bolditalic("GR400/+"), bold("12.5 wk"))),
    "C9ORF72-GR400-B6J:Het_64.5" = bquote(atop(bolditalic("\u2003C9orf72")^bolditalic("GR400/+"), bold("64.5 wk")))
  ))+ # Custom labels for genotype and age
  theme_classic(base_size = 8) + # classic theme makes white background without lines, sets base font size to 14 pt
  theme(
    text = element_text(family = "Arial"),
    legend.position = c(0.35, 0.92), # Position legend within plotting space
        legend.direction = "horizontal", # Arrange legend items horizontally
        legend.text.align = 0,
        legend.spacing.y = unit(0, "cm"), # Remove vertical spacing between items
        legend.margin = margin(0, 0, 0, 0)  ,      
        legend.text = element_text(size = 8, family = "Arial"), # Set font size for legend text
        legend.title = element_text(size = 8, face = "bold", family = "Arial"), # Set font size for legend title
        axis.title.y = element_text(size = 8, face = "bold", family = "Arial"), 
  axis.text.x = element_text(size = 8, colour="black", family = "Arial"), # Adjust vertical alignment        
  axis.text.y = element_text(size = 8, colour = "black", family = "Arial"),
        legend.background = element_rect(fill = NA, colour = NA)) + # Rotate x-axis labels for better readability
  scale_colour_manual(name = NULL, # sets the legend title     
                      breaks = c("C9ORF72-GR400-B6J:WT", "C9ORF72-GR400-B6J:Het"), # sets the order of items in the legend
                      labels = c("WT", expression(italic("C9orf72")^italic("GR400/+"))), # sets the labels of items in the legend
                      values = c("#009E73", "#332288")) + # set line colours for points
  scale_shape_manual(name = "Age (weeks)", # sets the legend title for shape
                     values = c("12.5" = 1, "64.5" = 16))+  # set shapes for ages (1 = empty circle, 16 = filled circle)
  guides(
    colour = guide_legend(order = 1, override.aes = list(shape=NA)), # Use only lines for Genotype
    shape = guide_legend(order = 2) # Keep shape legend for Age (weeks)
  )
# Save the plot
ggsave("C9_NPR_dur_av_600_col-arial.tiff", plot = pEXPL_NPR_t, width = 3.5, height = 3, dpi = 600)  # Adjust width, height, and dpi as needed and save the image in the folder where the code file is

# Display the plot
pEXPL_NPR_t



```





***LMER - NPR -frequency***
```{r}
#relevel the data to compare everything in the model to control mice
data_mouse$genotype <- relevel(data_mouse$genotype, ref = "C9ORF72-GR400-B6J:WT")

#linear mixed effects model 
ME_EXPL_nprf<- lmer(NPRfreq~genotype*(mean_experimental_age + sex + inh) + (1|animal_name),data = data_mouse)
summary(ME_EXPL_nprf)
resid_panel(ME_EXPL_nprf) 
anova(ME_EXPL_nprf, type=3)
#Post-hoc - relevant contrasts
emm_nprf <- emmeans(ME_EXPL_nprf, ~genotype*mean_experimental_age)
str(emm_nprf)
coef_t_nprf <- coef(pairs(emm_nprf))
custom_contrasts_nprf <- list(
                         "12.5 Wt vs Het" = c(1, -1, 0, 0),
                         "64.5 Wt vs Het" = c(0, 0, 1, -1)
                         )
specific_comparisons_nprf <-contrast(emm_nprf, custom_contrasts_nprf)
summary_comparisons_nprf <- summary(specific_comparisons_nprf, adjust="bonferroni")
p_value_nprf <- summary_comparisons_nprf$p.value
print(p_value_nprf)
print(summary_comparisons_nprf)

```


***Plot NPR based on frequency by age and genotype***

```{r}
# take means and se per group for plotting Duration


EXPL_NPR_f <- ddply(data_mouse, c("mean_experimental_age", "genotype"), summarise,
               N    = length(NPRfreq),
               mean = mean(NPRfreq, na.rm = TRUE),
               sd   = sd(NPRfreq, na.rm = TRUE),
               se   = sd / sqrt(N)
)


# Ensure the factor levels are ordered as desired
EXPL_NPR_f$mean_experimental_age <- factor(EXPL_NPR_f$mean_experimental_age, levels = c("12.5", "64.5"))
data_mouse$mean_experimental_age <- factor(data_mouse$mean_experimental_age, levels = c("12.5", "64.5"))

# Combine genotype and age for the x-axis and set specific levels to control order and spacing
EXPL_NPR_f$genotype_age <- factor(paste(EXPL_NPR_f$genotype, EXPL_NPR_f$mean_experimental_age, sep = "_"),
                                  levels = c("C9ORF72-GR400-B6J:WT_12.5", "C9ORF72-GR400-B6J:WT_64.5", 
                                             "C9ORF72-GR400-B6J:Het_12.5", "C9ORF72-GR400-B6J:Het_64.5"))
data_mouse$genotype_age <- factor(paste(data_mouse$genotype, data_mouse$mean_experimental_age, sep = "_"),
                                levels = c("C9ORF72-GR400-B6J:WT_12.5", "C9ORF72-GR400-B6J:WT_64.5", 
                                           "C9ORF72-GR400-B6J:Het_12.5", "C9ORF72-GR400-B6J:Het_64.5"))

# Plot averages per group
pEXPL_NPR_f <- ggplot(EXPL_NPR_f, aes(x = genotype_age, y = mean, colour = genotype)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.3), width = 0.5, alpha = 0) + 
  geom_jitter(data = data_mouse, aes(x = genotype_age, y = NPRfreq, colour = genotype, shape = mean_experimental_age), 
              position = position_jitterdodge(jitter.width = 0.5, dodge.width = 0.3), size = 0.8) + # Add individual data points
   geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey50") + # Add a dashed line at y = 0.5

   geom_errorbar(aes(ymin = mean - se, ymax = mean + se), 
                width = 0.2, position = position_dodge(0.75), colour = "black") + # Add error bars
  # Add a dummy line layer for the legend
  ylab("NPR based on frequency") + # sets the y-axis label
  scale_y_continuous(breaks = seq(0, 1.5, by = 0.5), limits = c(0, 1.5), expand = c(0, 0)) +  # Set y-axis breaks with step size of 0.1
  xlab(NULL) + # sets the x-axis label
  scale_x_discrete(labels = c(
    "C9ORF72-GR400-B6J:WT_12.5" = bquote(bold(atop("WT", "12.5 wk"))),
    "C9ORF72-GR400-B6J:WT_64.5" = bquote(bold(atop("WT", "64.5 wk"))),
    "C9ORF72-GR400-B6J:Het_12.5" = bquote(atop(bolditalic("C9orf72")^bolditalic("GR400/+"), bold("12.5 wk"))),
    "C9ORF72-GR400-B6J:Het_64.5" = bquote(atop(bolditalic("\u2003C9orf72")^bolditalic("GR400/+"), bold("64.5 wk")))
  ))+ # Custom labels for genotype and age
  theme_classic(base_size = 8) + # classic theme makes white background without lines, sets base font size to 14 pt
  theme(
    text = element_text(family = "Arial"),
    legend.position = c(0.35, 0.92), # Position legend within plotting space
        legend.direction = "horizontal", # Arrange legend items horizontally
        legend.text.align = 0,
        legend.spacing.y = unit(0, "cm"), # Remove vertical spacing between items
        legend.margin = margin(0, 0, 0, 0)  ,      
        legend.text = element_text(size = 8, family = "Arial"), # Set font size for legend text
        legend.title = element_text(size = 8, face = "bold", family = "Arial"), # Set font size for legend title
        axis.title.y = element_text(size = 8, face = "bold", family = "Arial"), 
  axis.text.x = element_text(size = 8, colour="black", family = "Arial"), # Adjust vertical alignment        
  axis.text.y = element_text(size = 8, colour = "black", family = "Arial"),
        legend.background = element_rect(fill = NA, colour = NA)) + # Rotate x-axis labels for better readability
  scale_colour_manual(name = NULL, # sets the legend title     
                      breaks = c("C9ORF72-GR400-B6J:WT", "C9ORF72-GR400-B6J:Het"), # sets the order of items in the legend
                      labels = c("WT", expression(italic("C9orf72")^italic("GR400/+"))), # sets the labels of items in the legend
                      values = c("#009E73", "#332288")) + # set line colours for points
  scale_shape_manual(name = "Age (weeks)", # sets the legend title for shape
                     values = c("12.5" = 1, "64.5" = 16))+  # set shapes for ages (1 = empty circle, 16 = filled circle)
  guides(
    colour = guide_legend(order = 1, override.aes = list(shape=NA)), # Use only lines for Genotype
    shape = guide_legend(order = 2) # Keep shape legend for Age (weeks)
  )


# Add significance stars using geom_signif
pEXPL_NPR_f <- pEXPL_NPR_f +
  geom_signif(comparisons = list(
    c("C9ORF72-GR400-B6J:WT_64.5", "C9ORF72-GR400-B6J:Het_64.5")
  ),
  annotations = c(
    ifelse(p_value_novel[2] < 0.0001, "****",
           ifelse(p_value_novel[2] < 0.001, "***",
               ifelse(p_value_novel[2] < 0.01, "**",
                  ifelse(p_value_novel[2] < 0.05, "*", ""))))
  ),
  y_position = c(0.9), # Adjust positions as needed
  tip_length = 0.02, textsize = 7,
  color = "black", family = "Arial")



# Save the plot
ggsave("C9_NPR_freq_av_600_col-arial.tiff", plot = pEXPL_NPR_f, width = 3.5, height = 3, dpi = 600)  # Adjust width, height, and dpi as needed and save the image in the folder where the code file is
# Display the plot
pEXPL_NPR_f


```


