---
title: "C9orf72 mice - optokinetic drum (OKD) analysis"
output: html_document
date: "2024-12-19"
---
***Load libraries and data***

```{r}
library(readr)
library(forcats)
library(lme4)
library(ggplot2)
library(lmerTest)
library(emmeans)
library(ggResidpanel)
library(plyr)
library(dplyr)
library(car)
library(ggsignif)
library(table1)


setwd("~/Desktop/Data/OKD/")

# read in data 
data_mouse <- read_csv("C9-okd-upd_standard_harmonised.csv", col_types = cols (
  animal_name = 'f',
  genotype = 'f',
  sex = 'f',
  inh = 'f',
  mean_experimental_age = 'f'
))
#inh = inheritance
data_mouse$genotypeordered <- ordered(data_mouse$genotype, levels=c("C9ORF72-GR400-B6J:Het", "C9ORF72-GR400-B6J:WT"))
data_mouse$genotype <- as.factor(data_mouse$genotype)
data_mouse$sex <- as.factor(data_mouse$sex)
data_mouse$inh <- as.factor(data_mouse$inh)
data_mouse$mean_experimental_age <- as.factor(data_mouse$mean_experimental_age)

table1::label(data_mouse$genotype) <- "genotype"
table1::label(data_mouse$mean_experimental_age) <- "age"
table1::label(data_mouse$sex) <- "sex"

	
table1::table1(~  mean_experimental_age | genotype, data = data_mouse)


```

***LMER - OKD***
```{r}
#relevel the data to compare everything in the model to control mice
data_mouse$genotype <- relevel(data_mouse$genotype, ref = "C9ORF72-GR400-B6J:WT")

#linear mixed effects model 
ME_EXPL<- lmer(acuity~genotype*(sex + mean_experimental_age + inh) +(1|animal_name),data = data_mouse)
summary(ME_EXPL)
resid_panel(ME_EXPL) 
anova(ME_EXPL, type=3)

#Post-hoc - relevant contrasts
emm <- emmeans(ME_EXPL, ~genotype*mean_experimental_age)
str(emm)
coef_t_okd <- coef(pairs(emm))
custom_contrasts <- list("Wt 15 vs 68 weeks" = c(1, 0, -1, 0),
                         "Het 15 vs 68 weeks" = c(0, 1, 0, -1))
specific_comparisons <-contrast(emm, custom_contrasts)
summary_comparisons <- summary(specific_comparisons, adjust="bonferroni")
p_value <- summary_comparisons$p.value
print(p_value)

# Print the summary of the comparisons
print(summary_comparisons)

```



***Plot visual acuity by age and genotype***

```{r}

# take means and se per group for plotting Duration

EXPL_vis <- ddply(data_mouse, c("mean_experimental_age", "genotype"), summarise,
               N    = length(acuity),
               mean = mean(acuity, na.rm = TRUE),
               sd   = sd(acuity, na.rm = TRUE),
               se   = sd / sqrt(N)
)


# Ensure the factor levels are ordered as desired
EXPL_vis$mean_experimental_age <- factor(EXPL_vis$mean_experimental_age, levels = c("15", "68"))
data_mouse$mean_experimental_age <- factor(data_mouse$mean_experimental_age, levels = c("15", "68"))

# Combine genotype and age for the x-axis and set specific levels to control order and spacing
EXPL_vis$genotype_age <- factor(paste(EXPL_vis$genotype, EXPL_vis$mean_experimental_age, sep = "_"),
                                  levels = c("C9ORF72-GR400-B6J:WT_15", "C9ORF72-GR400-B6J:WT_68", 
                                             "C9ORF72-GR400-B6J:Het_15", "C9ORF72-GR400-B6J:Het_68"))
data_mouse$genotype_age <- factor(paste(data_mouse$genotype, data_mouse$mean_experimental_age, sep = "_"),
                                levels = c("C9ORF72-GR400-B6J:WT_15", "C9ORF72-GR400-B6J:WT_68", 
                                             "C9ORF72-GR400-B6J:Het_15", "C9ORF72-GR400-B6J:Het_68"))

# Plot averages per group
pEXPL_vis <- ggplot(EXPL_vis, aes(x = genotype_age, y = mean, colour = genotype)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.3), width = 0.5, alpha = 0) + 
  geom_jitter(data = data_mouse, aes(x = genotype_age, y = acuity, colour = genotype, shape = mean_experimental_age), 
              position = position_jitterdodge(jitter.width = 0.5, dodge.width = 0.3), size = 0.8) + # Add individual data points
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), 
                width = 0.2, position = position_dodge(0.75), colour = "black") + # Add error bars
  # Add a dummy line layer for the legend
  ylab("Spatial frequency (cycles/degree)") + # sets the y-axis label
  scale_y_continuous(breaks = seq(0, 1, by = 0.2), limits = c(0, 1), expand = c(0, 0)) +  # Set y-axis breaks with step size of 0.1
  xlab(NULL) + # sets the x-axis label
  scale_x_discrete(labels = c(
    "C9ORF72-GR400-B6J:WT_15" = bquote(bold(atop("WT", "15 wk"))),
    "C9ORF72-GR400-B6J:WT_68" = bquote(bold(atop("WT", "68 wk"))),
    "C9ORF72-GR400-B6J:Het_15" = bquote(atop(bolditalic("C9orf72")^bolditalic("GR400/+"), bold("15 wk"))),
    "C9ORF72-GR400-B6J:Het_68" = bquote(atop(bolditalic("C9orf72")^bolditalic("GR400/+"), bold("68 wk")))
  ))+ # Custom labels for genotype and age
  theme_classic(base_size = 8) + # classic theme makes white background without lines, sets base font size to 14 pt
  theme(text = element_text(family = "Arial"),
    legend.position = c(0.35, 0.92), # Position legend within plotting space
        legend.direction = "horizontal", # Arrange legend items horizontally
        legend.text.align = 0,
        legend.spacing.y = unit(0, "cm"), # Remove vertical spacing between items
        legend.margin = margin(0, 0, 0, 0)  ,      
        legend.text = element_text(size = 8, family = "Arial"), # Set font size for legend text
        legend.title = element_text(size = 8, face = "bold", family = "Arial"), # Set font size for legend title
        axis.title.y = element_text(size = 8, face = "bold", family = "Arial"), 
  axis.text.x = element_text(size = 8, colour="black", family = "Arial"), # Adjust vertical alignment        
  axis.text.y = element_text(size = 8, colour = "black", family = "Arial"),
        legend.background = element_rect(fill = NA, colour = NA)) + # Rotate x-axis labels for better readability
  scale_colour_manual(name = NULL, # sets the legend title     
                      breaks = c("C9ORF72-GR400-B6J:WT", "C9ORF72-GR400-B6J:Het"), # sets the order of items in the legend
                      labels = c("WT", expression(italic("C9orf72")^italic("GR400/+"))), # sets the labels of items in the legend
                      values = c("#009E73", "#332288")) + # set line colours for points
  scale_shape_manual(name = "Age (weeks)", # sets the legend title for shape
                     values = c("15" = 1, "68" = 16))+  # set shapes for ages (1 = empty circle, 16 = filled circle)
  guides(
    colour = guide_legend(order = 1, override.aes = list(shape=NA)), # Use only lines for Genotype
    shape = guide_legend(order = 2) # Keep shape legend for Age (weeks)
  )

# Add significance stars using geom_signif
pEXPL_vis <- pEXPL_vis +
  geom_signif(comparisons = list(
    c("C9ORF72-GR400-B6J:WT_15", "C9ORF72-GR400-B6J:WT_68"),
    c("C9ORF72-GR400-B6J:Het_15", "C9ORF72-GR400-B6J:Het_68")
    
  ),
  annotations = c(
    ifelse(p_value[1] < 0.0001, "****",
           ifelse(p_value[1] < 0.001, "***",
               ifelse(p_value[1] < 0.01, "**",
                  ifelse(p_value[1] < 0.05, "*", "ns")))),
    ifelse(p_value[2] < 0.0001, "****",
           ifelse(p_value[2] < 0.001, "***",
           ifelse(p_value[2] < 0.01, "**",
                  ifelse(p_value[2] < 0.05, "*", "ns"))))
   
  ),
  y_position = c(0.6, 0.6), # Adjust positions as needed
  tip_length = 0.02, textsize = 7,
  color = "black", family = "Arial")

# Save and display the plot
ggsave("C9_OKD_av_600-arial.tiff", plot = pEXPL_vis, width = 3.5, height = 3, dpi = 600)
print(pEXPL_vis)

```



